import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function drawWrappedText(page: any, text: string, x: number, y: number, maxWidth: number, font: any, size: number, color: any, lineHeight: number) {
  const words = text.split(" ");
  let line = "";
  let currentY = y;
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(test, size) > maxWidth && line) {
      page.drawText(line, { x, y: currentY, size, font, color });
      currentY -= lineHeight;
      line = word;
    } else {
      line = test;
    }
  }
  if (line) {
    page.drawText(line, { x, y: currentY, size, font, color });
    currentY -= lineHeight;
  }
  return currentY;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(
      authHeader.replace("Bearer ", "")
    );
    if (claimsError || !claimsData?.claims) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { interviewId } = await req.json();

    const serviceClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: interview } = await serviceClient
      .from("interviews")
      .select("*, countries(name), visa_types(name), interview_reports(*)")
      .eq("id", interviewId)
      .single();

    if (!interview) {
      return new Response(JSON.stringify({ error: "Interview not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const report = interview.interview_reports;
    const countryName = (interview.countries as any)?.name || "Unknown";
    const visaType = (interview.visa_types as any)?.name || "Unknown";
    const date = new Date(interview.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

    const grammarMistakes = Array.isArray(report?.grammar_mistakes) ? report.grammar_mistakes : [];
    const redFlags = Array.isArray(report?.red_flags) ? report.red_flags : [];
    const improvementPlan = Array.isArray(report?.improvement_plan) ? report.improvement_plan : [];

    // Create PDF
    const pdfDoc = await PDFDocument.create();
    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const pageWidth = 595;
    const pageHeight = 842;
    const margin = 50;
    const maxWidth = pageWidth - margin * 2;
    const black = rgb(0, 0, 0);
    const gray = rgb(0.4, 0.4, 0.4);
    const accent = rgb(0.09, 0.58, 0.36);

    let page = pdfDoc.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;

    function ensureSpace(needed: number) {
      if (y - needed < margin + 30) {
        // Footer on current page
        page.drawText("Generated by Visa Cracked", { x: margin, y: margin - 10, size: 8, font: fontRegular, color: gray });
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        y = pageHeight - margin;
      }
    }

    // Embed logo
    try {
      const logoUrl = "https://visa-cracked.lovable.app/lovable-uploads/6cf51dda-1653-4e1e-be84-bc5e41e2a498.png";
      const logoResponse = await fetch(logoUrl);
      if (logoResponse.ok) {
        const logoBytes = new Uint8Array(await logoResponse.arrayBuffer());
        const logoImage = await pdfDoc.embedPng(logoBytes);
        const logoDims = logoImage.scale(0.4);
        page.drawImage(logoImage, { x: margin, y: y - logoDims.height, width: logoDims.width, height: logoDims.height });
        y -= logoDims.height + 20;
      }
    } catch {
      // Skip logo if fetch fails
    }

    // Title
    page.drawText("MOCK TEST REPORT", { x: margin, y, size: 18, font: fontBold, color: black });
    y -= 30;

    // Info
    const infoLines = [
      `Mock Name:  ${interview.name || "N/A"}`,
      `Country:    ${countryName}`,
      `Visa Type:  ${visaType}`,
      `Date:       ${date}`,
    ];
    for (const line of infoLines) {
      page.drawText(line, { x: margin, y, size: 10, font: fontRegular, color: gray });
      y -= 16;
    }
    y -= 10;

    // Scores section
    page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
    y -= 20;
    page.drawText("SCORES", { x: margin, y, size: 12, font: fontBold, color: black });
    y -= 20;

    const scores = [
      ["Overall Score", report?.overall_score],
      ["English", report?.english_score],
      ["Confidence", report?.confidence_score],
      ["Financial Clarity", report?.financial_clarity_score],
      ["Immigration Intent", report?.immigration_intent_score],
      ["Pronunciation", report?.pronunciation_score],
      ["Vocabulary", report?.vocabulary_score],
      ["Response Relevance", report?.response_relevance_score],
    ];

    for (const [label, score] of scores) {
      const val = score != null ? `${score}/100` : "N/A";
      page.drawText(label as string, { x: margin, y, size: 10, font: fontRegular, color: gray });
      page.drawText(val, { x: margin + 180, y, size: 10, font: fontBold, color: score != null && (score as number) >= 80 ? accent : black });
      y -= 16;
    }

    // Grammar Mistakes
    if (grammarMistakes.length > 0) {
      ensureSpace(60);
      y -= 10;
      page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
      y -= 20;
      page.drawText(`GRAMMAR MISTAKES (${grammarMistakes.length})`, { x: margin, y, size: 12, font: fontBold, color: black });
      y -= 20;

      for (const m of grammarMistakes as any[]) {
        ensureSpace(40);
        page.drawText(`"${m.original}" -> "${m.corrected}"`, { x: margin, y, size: 10, font: fontRegular, color: black });
        y -= 14;
        if (m.explanation) {
          y = drawWrappedText(page, m.explanation, margin + 10, y, maxWidth - 10, fontRegular, 9, gray, 13);
          y -= 4;
        }
      }
    }

    // Red Flags
    if (redFlags.length > 0) {
      ensureSpace(60);
      y -= 10;
      page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
      y -= 20;
      page.drawText("RED FLAGS", { x: margin, y, size: 12, font: fontBold, color: black });
      y -= 20;

      for (const flag of redFlags as string[]) {
        ensureSpace(30);
        y = drawWrappedText(page, `• ${flag}`, margin, y, maxWidth, fontRegular, 10, gray, 14);
        y -= 4;
      }
    }

    // Improvement Plan
    if (improvementPlan.length > 0) {
      ensureSpace(60);
      y -= 10;
      page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
      y -= 20;
      page.drawText("IMPROVEMENT PLAN", { x: margin, y, size: 12, font: fontBold, color: black });
      y -= 20;

      improvementPlan.forEach((item: string, i: number) => {
        ensureSpace(30);
        y = drawWrappedText(page, `${i + 1}. ${item}`, margin, y, maxWidth, fontRegular, 10, gray, 14);
        y -= 4;
      });
    }

    // AI Summary
    if (report?.summary) {
      ensureSpace(60);
      y -= 10;
      page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
      y -= 20;
      page.drawText("AI SUMMARY", { x: margin, y, size: 12, font: fontBold, color: black });
      y -= 20;
      y = drawWrappedText(page, report.summary, margin, y, maxWidth, fontRegular, 10, gray, 14);
    }

    // Transcript as chat bubbles
    const messages = interview.messages;
    if (Array.isArray(messages) && messages.length > 0) {
      ensureSpace(60);
      y -= 10;
      page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
      y -= 20;
      page.drawText("CONVERSATION TRANSCRIPT", { x: margin, y, size: 12, font: fontBold, color: black });
      y -= 20;

      for (const msg of messages as any[]) {
        if (!msg.content) continue;
        const isUser = msg.role === "user";
        const label = isUser ? "You:" : "Officer:";
        const indent = isUser ? margin + 80 : margin;
        const textWidth = isUser ? maxWidth - 80 : maxWidth - 80;
        ensureSpace(30);
        page.drawText(label, { x: indent, y, size: 9, font: fontBold, color: isUser ? accent : gray });
        y -= 13;
        y = drawWrappedText(page, msg.content, indent, y, textWidth, fontRegular, 9, gray, 12);
        y -= 8;
      }
    } else if (interview.transcript) {
      ensureSpace(60);
      y -= 10;
      page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.5, color: gray });
      y -= 20;
      page.drawText("FULL TRANSCRIPT", { x: margin, y, size: 12, font: fontBold, color: black });
      y -= 20;

      const lines = interview.transcript.split("\n");
      for (const line of lines) {
        ensureSpace(20);
        y = drawWrappedText(page, line || " ", margin, y, maxWidth, fontRegular, 9, gray, 13);
      }
    }

    // Footer on last page
    page.drawText("Generated by Visa Cracked", { x: margin, y: margin - 10, size: 8, font: fontRegular, color: gray });

    const pdfBytes = await pdfDoc.save();
    const base64 = btoa(String.fromCharCode(...pdfBytes));

    const safeName = (interview.name || "report").replace(/[^a-zA-Z0-9]/g, "-").toLowerCase();
    return new Response(
      JSON.stringify({ pdf: base64, filename: `visa-cracked-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf` }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
